#!/bin/bash
# GENERATED CODE VERIFICATION SCRIPT
# Use to check for stale generated artifacts and verify regeneration commands

set -e

REPO_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
DASHBOARD_DIR="$REPO_ROOT/dashboard"

echo "🔍 GENERATED CODE VERIFICATION REPORT"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Repository: $REPO_ROOT"
echo "Scan Date: $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
echo ""

# 1. Check .next/ existence
echo "1️⃣  Next.js Build Output (.next/)"
if [ -d "$DASHBOARD_DIR/.next" ]; then
    SIZE=$(du -sh "$DASHBOARD_DIR/.next" 2>/dev/null | cut -f1)
    MODIFIED=$(stat -f %Sm -t "%Y-%m-%d %H:%M:%S" "$DASHBOARD_DIR/.next" 2>/dev/null || echo "N/A")
    echo "   ✅ EXISTS | Size: $SIZE | Modified: $MODIFIED"
    echo "   ⚠️  RULE: Never commit. Regenerate with: npm run build"
else
    echo "   ❌ MISSING (will be created on next build)"
fi
echo ""

# 2. Check Prisma generated client
echo "2️⃣  Prisma Generated Client (src/generated/prisma/)"
if [ -d "$DASHBOARD_DIR/src/generated/prisma" ]; then
    FILE_COUNT=$(find "$DASHBOARD_DIR/src/generated/prisma" -type f | wc -l)
    MODIFIED=$(stat -f %Sm -t "%Y-%m-%d %H:%M:%S" "$DASHBOARD_DIR/src/generated/prisma" 2>/dev/null || echo "N/A")
    echo "   ✅ EXISTS | Files: $FILE_COUNT | Modified: $MODIFIED"
    
    # Check for marker
    if grep -q "This is code generated by Prisma" "$DASHBOARD_DIR/src/generated/prisma/client.ts" 2>/dev/null; then
        echo "   ✅ Generation markers present (client.ts line 2)"
    else
        echo "   ⚠️  No Prisma marker found in client.ts"
    fi
    echo "   ⚠️  RULE: Never commit. Regenerate with: npm run prisma:generate"
else
    echo "   ❌ MISSING (run: npm run prisma:generate)"
fi
echo ""

# 3. Check schema.prisma
echo "3️⃣  Schema Source (prisma/schema.prisma)"
if [ -f "$DASHBOARD_DIR/prisma/schema.prisma" ]; then
    echo "   ✅ EXISTS"
    GENERATOR_CONFIG=$(grep -A 3 "generator client" "$DASHBOARD_DIR/prisma/schema.prisma" || echo "NOT FOUND")
    if [ "$GENERATOR_CONFIG" != "NOT FOUND" ]; then
        echo "   ✅ Generator config found (lines 4-6)"
        OUTPUT_PATH=$(echo "$GENERATOR_CONFIG" | grep "output" | sed 's/.*"\(.*\)".*/\1/')
        echo "   📁 Output: $OUTPUT_PATH"
    else
        echo "   ⚠️  No generator config found"
    fi
    echo "   📋 RULE: Edit this file, then run: npm run prisma:generate"
else
    echo "   ❌ MISSING (critical!)"
fi
echo ""

# 4. Check .gitignore rules
echo "4️⃣  .gitignore Compliance"
GIT_IGNORE_RULES=(".next/" "out/" "build/" "dist/" "/src/generated/" "next-env.d.ts")
for rule in "${GIT_IGNORE_RULES[@]}"; do
    if grep -q "^$rule" "$REPO_ROOT/.gitignore" 2>/dev/null; then
        echo "   ✅ $rule is gitignored"
    else
        echo "   ❌ $rule is NOT in .gitignore"
    fi
done
echo ""

# 5. Check for uncommitted generated artifacts
echo "5️⃣  Git Status (Generated Files)"
if command -v git &> /dev/null && [ -d "$REPO_ROOT/.git" ]; then
    GIT_STAGED=$(cd "$REPO_ROOT" && git diff --cached --name-only | grep -E "\.next/|src/generated/|build/|dist/" || echo "")
    if [ -z "$GIT_STAGED" ]; then
        echo "   ✅ No generated artifacts staged for commit"
    else
        echo "   ⚠️  WARNING: Generated files staged for commit:"
        echo "$GIT_STAGED" | sed 's/^/      /'
    fi
else
    echo "   ⏭️  Git not available or not a repo"
fi
echo ""

# 6. Package.json scripts check
echo "6️⃣  Build Scripts (package.json)"
SCRIPTS=("prisma:generate" "build" "predev" "prebuild" "typecheck" "pretest")
for script in "${SCRIPTS[@]}"; do
    if grep -q "\"$script\"" "$DASHBOARD_DIR/package.json" 2>/dev/null; then
        echo "   ✅ $script script found"
    else
        echo "   ❌ $script script NOT found"
    fi
done
echo ""

# 7. Anti-pattern check (sample files)
echo "7️⃣  Anti-Pattern Detection"
SAMPLE_FILES=(
    "$DASHBOARD_DIR/src/generated/prisma/client.ts:Prisma client.ts"
    "$DASHBOARD_DIR/.next/build-manifest.json:Next.js manifest"
)

for file_info in "${SAMPLE_FILES[@]}"; do
    IFS=':' read -r filepath desc <<< "$file_info"
    if [ -f "$filepath" ]; then
        if head -5 "$filepath" | grep -qE "generated|@generated|AUTO-GENERATED|DO NOT EDIT"; then
            echo "   ✅ $desc has generation marker"
        else
            echo "   ℹ️  $desc (no obvious marker, but still auto-generated)"
        fi
    fi
done
echo ""

# 8. Recommendations
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 REGENERATION COMMANDS"
echo ""
echo "After schema changes:"
echo "  cd $DASHBOARD_DIR && npm run prisma:generate"
echo ""
echo "Before deploying:"
echo "  cd $DASHBOARD_DIR && npm run build"
echo ""
echo "Full clean rebuild:"
echo "  cd $DASHBOARD_DIR && rm -rf .next src/generated node_modules"
echo "  npm install && npm run build"
echo ""
echo "Type-check (triggers prisma:generate):"
echo "  cd $DASHBOARD_DIR && npm run typecheck"
echo ""

# 9. References
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📚 REFERENCE FILES"
echo ""
echo "  • GENERATED_CODE_REGISTRY.md         — Comprehensive registry (human-readable)"
echo "  • AGENTS_GENERATED_CODE_RULES.md     — Quick reference for AI agents"
echo "  • .generated-code-manifest.json      — Machine-readable manifest"
echo ""
