name: All Contributors

on:
  pull_request_target:
    types: [closed]

jobs:
  add-contributor:
    if: github.event.pull_request.merged == true && github.event.pull_request.user.login != 'github-actions[bot]' && github.event.pull_request.user.login != 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
        with:
          ref: main

      - uses: JoshuaKGoldberg/all-contributors-auto-action@v0.6.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
